spring:
   #redis相关配置
  redis:
   host: 127.0.0.1
   port: 36379
   timeout: 360000
   pool:
     max-active: 8
     max-wait: -1
     max-idle: 10
     min-idle: 0

#日志配置
logging:
  level: 
    org.apache.zookeeper: off
    com.alibaba: off
    
#端口配置    
server:
  port: 10002
  session:
    timeout: 30
  tomcat:
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    basedir: /tmp
    accesslog:
      enabled: true
      directory: /logs/puhui-tomcat/app-api-merchant
      pattern: common
      prefix: phshopping-
      suffix: .log
    uri-encoding: UTF-8

